spring:
  mail:
    protocol: smtps
    #配置smtp服务器地址
    host: smtp.qq.com
    #发送者邮箱
    username: 1085444086@qq.com
    #配置密码 注意不是真正的密码，而是刚刚申请到的授权码
    password: vavdlippioseidfb
    #端口号465或者587
    port: 465
    #默认邮件编码为UTF-8
    default-encoding: UTF-8